---
sudo: required
language: ruby
cache: bundler

services:
  - docker

matrix:
  include:
  - rvm: 1.9.3
    gemfile: Gemfile
  - rvm: 2.0
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
    script: bundle exec rake test test:resources
